# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'maximsandersaolcom_ma_892' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HelpMeFeedParent
  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'FBSDKCoreKit', '~> 5.0.0'
  pod 'FBSDKLoginKit', '~> 5.0.0'
  pod 'FBSDKShareKit', '~> 5.0.0'
  
  pod 'GoogleSignIn', '~> 4.4.0'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk/'
  pod 'react-native-blur', :path => '../node_modules/react-native-blur/'
  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
    'BarcodeDetectorMLKit'
  ]

  target 'maximsandersaolcom_ma_892Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'maximsandersaolcom_ma_892-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# very important to have, unless you removed React dependencies for Libraries 
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    targets_to_ignore = %w(React yoga)
      
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

  end
end

