export default {
  IntroScreen: 'IntroScreen',
  TestScreen: 'TestScreen',
  LoginScreen: 'LoginScreen',
  RegisterScreen: 'RegisterScreen',
  ProfileScreen: 'ProfileScreen',
  EditProfileScreen: 'EditProfileScreen',
  NotificationScreen: 'NotificationScreen',
  SavedProgramsScreen: 'SavedProgramsScreen',
  NutritionScreen: 'NutritionScreen',
  FeedScreen: 'FeedScreen',
  BarCodeScreen: 'BarCodeScreen',
  FindFoodAndRecipesScreen: 'FindFoodAndRecipesScreen',
  IndividualRecipeScreen: 'IndividualRecipeScreen',
  IngredientScreen: 'IngredientScreen',
  IngredientRecipeScreen: 'IngredientRecipeScreen',
  TodayScreen: 'TodayScreen',
  ProgramScreen: 'ProgramScreen',
  ExerciseScreen: 'ExerciseScreen'
};
