export default {
  scannedProduct: null,
  meals: [
    {
      id: 1,
      date_time: `${new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate(), 8, 0).toISOString().substring(0, 19)}Z`,
      food_items: [],
      carbohydrate: 0,
      protein: 0,
      fat: 0,
      pieArray: [],
    },
    {
      id: 2,
      date_time: `${new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate(), 11, 0).toISOString().substring(0, 19)}Z`,
      food_items: [],
      carbohydrate: 0,
      protein: 0,
      fat: 0,
      pieArray: [],
    },
    {
      id: 3,
      date_time: `${new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate(), 14, 0).toISOString().substring(0, 19)}Z`,
      food_items: [],
      carbohydrate: 0,
      protein: 0,
      fat: 0,
      pieArray: [],
    },
    {
      id: 4,
      date_time: `${new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate(), 17, 0).toISOString().substring(0, 19)}Z`,
      food_items: [],
      carbohydrate: 0,
      protein: 0,
      fat: 0,
      pieArray: [],
    },
    {
      id: 5,
      date_time: `${new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate(), 20, 0).toISOString().substring(0, 19)}Z`,
      food_items: [],
      carbohydrate: 0,
      protein: 0,
      fat: 0,
      pieArray: [],
    },
    {
      id: 6,
      date_time: `${new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate(), 23, 0).toISOString().substring(0, 19)}Z`,
      food_items: [],
      carbohydrate: 0,
      protein: 0,
      fat: 0,
      pieArray: [],
    },
  ],
  recipes: [],
  error: [],
  categories: [],
  products: [],
  selectedProducts: [],
  selectedProductsStats: {
    calories: 0,
    proteins: 0,
    carbohydrate: 0,
    fat: 0
  },
  searchActive: false,
  searchStringState: '',
  selectedMeal: {}
};